#version 430

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout (binding = 0, rgba32f) uniform image2D outputImage;

void main() {
    // Get the coordinates of the pixel to write
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);

    imageStore(outputImage, pixel_coords, vec4(normalize(vec2(pixel_coords)),0.,1.) );
    //imageStore(outputImage, pixel_coords, vec4(1.,0.,0.,1.) );
}

